spring.application.name=logistics-service

spring.datasource.url=jdbc:postgresql://localhost:5432/vanopt_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true

vanopt.input-retention-days=30
vanopt.cleanup-cron=0 0 2 * * ?
